kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/minio-pv

