# -*- coding: utf-8 -*-

# Copyright 2018 Geobeyond Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 1.11.8 on 2018-08-31 15:56
from __future__ import unicode_literals

import app.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, storage=app.storage.MinioCogStorage(), upload_to='')),
                ('thumbnail', models.FileField(blank=True, null=True, storage=app.storage.MinioCogStorage(), upload_to='')),
                ('bucket_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'COG',
                'verbose_name_plural': 'COGs',
                'db_table': 'COG',
                'managed': True,
            },
        ),
    ]
