# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-05 06:05
from __future__ import unicode_literals

import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, storage=app.storage.MinioCogStorage(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'COG',
                'verbose_name_plural': 'COGs',
                'db_table': 'COG',
                'managed': True,
            },
        ),
    ]
