# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cog',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cog',
            name='resource_uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
