# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180806_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cog',
            name='id',
            field=models.UUIDField(default=uuid.UUID('583e55f8-265e-472f-b112-59bdd038c08a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
