# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 09:59

# Copyright 2018 Geobeyond Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180806_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cog',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af28929f-0496-4a44-b832-f11d4e74a495'), editable=False, primary_key=True, serialize=False),
        ),
    ]
