# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180806_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cog',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af28929f-0496-4a44-b832-f11d4e74a495'), editable=False, primary_key=True, serialize=False),
        ),
    ]
