apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-minio
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-2
  persistentVolumeReclaimPolicy: Recycle
