kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
  labels:
    type: local
    app: minio-container
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: local-volume-minio