kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
  labels:
    type: local
    app: db-container
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: local-volume-db